GET http://apis-student.onrender.com/
###

GET https://apis-student.onrender.com/students
###
POST https://apis-student.onrender.com/students
Content-Type: application/json

{
    "name":"K Anil Babu",
    "course":"MCA",
    "deptName":"Dept of Computer Science",
    "mobileNo":"975102615"
}
###

PUT http://apis-student.onrender.com/students
Content-Type: application/json

{
    "admNo":202102119,
    "name":"Anil Babu Katika",
    "course":"MCA",
    "deptName":"Dept of Computer Science",
    "mobileNo":"9314876534"
}
###

GET http://localhost:3000/students/202102119
###


DELETE http://localhost:3000/students/202102104
###


GET https://oembed.com/providers.json