GET http://apis-student.onrender.com/
###

GET https://apis-student.onrender.com/students
###
POST https://localhost:3000/students
Content-Type: application/json

{
    "name":"P sasidhar ",
    "course":"MCA",
    "deptName":"Dept of Computer Science",
    "mobileNo":"931484523"
}
###

PUT http://localhost:3000/students
Content-Type: application/json

{
    "admNo":202102102,
    "name":"Basineini Sri Maikanta",
    "course":"MCA",
    "deptName":"Dept of Computer Science",
    "mobileNo":"931478523"
}
###

###
DELETE http://localhost:3000/students/202102102
###

GET http://localhost:3000/students